// Each entry is one intentional match. A duplicate English word never appears in the same deck.
window.KOTOBA_WORDS = {
  translation: [
    ['bright','明るい','明るい・輝いている','The room is bright in the morning.'],
    ['journey','旅','旅行・道のり','The journey took three days.'],
    ['forest','森','森林','We walked through the forest.'],
    ['curious','好奇心の強い','知りたがる','She is curious about science.'],
    ['gentle','優しい','穏やかな','He spoke in a gentle voice.'],
    ['improve','改善する','より良くする','Practice can improve your skills.'],
    ['discover','発見する','初めて見つける','They discovered a new path.'],
    ['patient','忍耐強い','辛抱強い','Please be patient with yourself.'],
    ['ancient','古代の','とても昔の','This is an ancient city.'],
    ['quiet','静かな','音が少ない','The street was quiet at night.'],
    ['simple','簡単な','複雑でない','The answer is simple.'],
    ['honest','正直な','うそをつかない','Thank you for being honest.'],
    ['rare','珍しい','めったにない','It is rare to see this bird.'],
    ['gather','集める','一か所に集める','We gather leaves in autumn.'],
    ['protect','守る','危険から守る','Trees protect the soil.'],
    ['create','作り出す','新しく作る','They create art together.'],
    ['arrive','到着する','目的地に着く','We arrive before noon.'],
    ['choose','選ぶ','複数から決める','Choose a book you like.'],
    ['support','支える','助ける・支援する','Friends support each other.'],
    ['reduce','減らす','量を小さくする','We need to reduce waste.'],
    ['explain','説明する','分かるように伝える','Can you explain the rule?'],
    ['remember','覚えている','忘れずにいる','I remember that day.'],
    ['prepare','準備する','前もって用意する','Prepare for the trip.'],
    ['promise','約束する','すると誓う','I promise to help you.'],
    ['wonder','不思議に思う','疑問を抱く','I wonder what happened.'],
    ['comfortable','快適な','心地よい','This chair is comfortable.'],
    ['valuable','価値のある','大切で役立つ','Your advice is valuable.']
  ],
  synonym: [
    ['happy','glad','うれしい','She was happy to see her friend.'],
    ['begin','start','始める','Let us begin the lesson.'],
    ['large','big','大きい','They live in a large house.'],
    ['quick','fast','速い','He gave a quick reply.'],
    ['silent','quiet','静かな','The room was silent.'],
    ['angry','mad','怒っている','She was angry about the mistake.'],
    ['tiny','small','とても小さい','A tiny bird sat on the branch.'],
    ['difficult','hard','難しい','This question is difficult.'],
    ['beautiful','pretty','美しい','The garden is beautiful.'],
    ['ill','sick','病気の','He felt ill yesterday.'],
    ['finish','complete','終える','We will finish the project today.'],
    ['assist','help','助ける','Can you assist me?'],
    ['purchase','buy','買う','They plan to purchase a car.'],
    ['reply','answer','答える','Please reply to my question.'],
    ['select','choose','選ぶ','Select the correct answer.'],
    ['calm','peaceful','穏やかな','The lake was calm.'],
    ['wealthy','rich','裕福な','The wealthy family donated money.'],
    ['rapid','swift','素早い','The river has a rapid flow.'],
    ['safe','secure','安全な','Keep your passport safe.'],
    ['idea','thought','考え','That is an interesting idea.'],
    ['error','mistake','間違い','I found an error in the report.'],
    ['look','see','見る','Look at the sky.'],
    ['afraid','scared','怖がっている','The child was afraid of the storm.'],
    ['gift','present','贈り物','She gave him a gift.'],
    ['kind','friendly','親切な','Our neighbor is kind.']
  ]
};

// Headwords selected from the NGSL Project's 1.2 lists. Japanese glosses,
// examples and synonym pairings are original to this game (see README.md).
window.KOTOBA_COURSES = {
  ngsl: window.KOTOBA_WORDS,
  tsl: {
    translation: [
      ['vacation','休暇','仕事や学校を休む期間','Our vacation begins next week.'],
      ['client','取引先','サービスを受ける顧客','The client approved the plan.'],
      ['airport','空港','飛行機が発着する場所','Please arrive at the airport early.'],
      ['memo','社内連絡','短い業務用の文書','I sent a memo to the team.'],
      ['reservation','予約','席や部屋を前もって確保すること','We made a reservation for two.'],
      ['supervisor','上司','仕事を監督する人','Ask your supervisor for help.'],
      ['refund','返金','支払ったお金を返すこと','You can request a refund.'],
      ['goods','商品','売買される品物','The goods arrived this morning.'],
      ['workshop','研修会','実践的に学ぶ会','She attended a design workshop.'],
      ['downtown','中心街','街の中心部','The office is downtown.'],
      ['deadline','締め切り','仕事を終える期限','The deadline is Friday.'],
      ['invoice','請求書','支払額を示す書類','The invoice was sent yesterday.'],
      ['brochure','パンフレット','案内用の小冊子','Read the travel brochure.'],
      ['accountant','会計士','会計を扱う専門家','The accountant checked the figures.'],
      ['clerk','事務員','窓口や事務を担当する人','The clerk printed a receipt.'],
      ['lobby','ロビー','建物の入口の広間','Meet me in the hotel lobby.'],
      ['applicant','応募者','仕事などに申し込む人','Each applicant has an interview.'],
      ['seminar','セミナー','少人数の講習会','The seminar starts at nine.'],
      ['technician','技術者','機器の保守などを行う人','A technician repaired the printer.'],
      ['fare','運賃','交通機関に払う料金','The train fare has increased.'],
      ['receipt','領収書','支払いの証明書','Keep the receipt for your records.'],
      ['luggage','手荷物','旅行に持って行く荷物','Leave your luggage at the desk.'],
      ['shipment','出荷品','発送される商品','The shipment will arrive tomorrow.'],
      ['rental','賃貸','料金を払って借りること','The rental includes insurance.'],
      ['warranty','保証','製品の修理などの約束','The phone has a one-year warranty.'],
      ['notify','知らせる','正式に連絡する','Please notify us of any changes.'],
      ['inventory','在庫','保管中の商品','We checked the inventory today.'],
      ['destination','目的地','向かう先','Tokyo is our final destination.'],
      ['postpone','延期する','予定を後の日に移す','They postponed the meeting.'],
      ['coupon','割引券','割引を受けるための券','Use this coupon at checkout.'],
      ['renovation','改装','建物を新しく直すこと','The store is closed for renovation.'],
      ['upgrade','改良する','より良いものに変える','We upgraded the software.'],
      ['passport','旅券','海外渡航に必要な身分証','Check your passport before leaving.'],
      ['coworker','同僚','同じ職場で働く人','My coworker helped with the report.'],
      ['appliance','家電製品','家庭で使う電気機器','This appliance saves energy.'],
      ['valid','有効な','規則上使える状態の','Your ticket is still valid.']
    ],
    synonym: [
      ['vacation','holiday','休暇','We went on vacation in August.'],
      ['client','customer','顧客','The client called this morning.'],
      ['supervisor','manager','管理者・上司','Speak with your supervisor.'],
      ['goods','products','商品','The goods are ready to ship.'],
      ['brochure','booklet','小冊子','Take a brochure from the desk.'],
      ['applicant','candidate','応募者','The applicant has strong skills.'],
      ['luggage','baggage','手荷物','Her luggage is quite heavy.'],
      ['shipment','delivery','配送品・配送','The shipment left today.'],
      ['warranty','guarantee','保証','The warranty covers repairs.'],
      ['notify','inform','知らせる','Please notify the team.'],
      ['obtain','get','手に入れる','You can obtain a copy online.'],
      ['inventory','stock','在庫','The store has limited inventory.'],
      ['postpone','delay','延期する','We need to postpone the event.'],
      ['upgrade','improve','改良する','The company upgraded its system.'],
      ['reservation','booking','予約','You can make a reservation online.'],
      ['depart','leave','出発する','The train will depart at noon.'],
      ['convenient','handy','便利な','The station is in a convenient location.'],
      ['replacement','substitute','代わりの物','We ordered a replacement part.'],
      ['rental','hire','賃借','Car rental is available here.'],
      ['upcoming','approaching','間近に迫った','Prepare for the upcoming event.']
    ]
  },
  nawl: {
    translation: [
      ['obtain','得る','努力して入手する','Researchers obtained new data.'],
      ['distribution','分布','物事が広がる状態','The chart shows the distribution.'],
      ['parameter','パラメータ','分析で値を設定する要素','We changed one parameter.'],
      ['aspect','側面','物事の一つの面','Consider every aspect of the issue.'],
      ['dynamic','動的な','変化し続ける','The market is highly dynamic.'],
      ['impact','影響','強い作用や効果','The policy had a major impact.'],
      ['domain','分野','研究などの対象領域','This is a complex domain.'],
      ['publish','発表する','研究成果などを公にする','They published the results.'],
      ['denote','表す','記号などで示す','The symbol denotes temperature.'],
      ['authority','権威','認められた力や専門性','The agency has legal authority.'],
      ['semantic','意味の','言葉の意味に関する','The study examines semantic change.'],
      ['matrix','行列','数値を縦横に並べたもの','The data are stored in a matrix.'],
      ['linear','直線的な','一直線の関係を持つ','They used a linear model.'],
      ['cognitive','認知の','思考や理解に関する','Sleep affects cognitive performance.'],
      ['correlation','相関','二つの事柄の関連','The study found a correlation.'],
      ['linguistic','言語の','言語学に関する','The paper studies linguistic patterns.'],
      ['induce','引き起こす','ある状態を生じさせる','The treatment may induce sleep.'],
      ['interval','間隔','二つの時点の隔たり','Measurements were taken at intervals.'],
      ['discourse','言説','まとまった話や文章','The article analyzes public discourse.'],
      ['finite','有限の','限りがある','Resources are finite.'],
      ['stimulus','刺激','反応を引き起こすもの','Light was used as a stimulus.'],
      ['simulation','模擬実験','現実を再現する実験','The simulation predicted the outcome.'],
      ['empirical','実証的な','観察や実験に基づく','We need empirical evidence.'],
      ['equilibrium','均衡','力などが釣り合う状態','The system reached equilibrium.'],
      ['intensity','強度','作用の強さ','The intensity of light increased.'],
      ['duration','期間','続く時間の長さ','Record the duration of the test.'],
      ['optimal','最適な','最も望ましい','Find the optimal solution.'],
      ['explicit','明示的な','はっきり示された','The instructions are explicit.'],
      ['dominant','支配的な','最も強い影響を持つ','One factor was dominant.'],
      ['prediction','予測','将来を見込むこと','The model makes a prediction.'],
      ['classification','分類','種類ごとに分けること','The classification has three levels.'],
      ['transmission','伝達','情報などを伝えること','The study examined transmission.'],
      ['occurrence','発生','出来事が起こること','The occurrence was unexpected.'],
      ['identical','同一の','まったく同じ','The two results are identical.'],
      ['rational','合理的な','理由や論理に基づく','They made a rational choice.'],
      ['integration','統合','複数のものを一つにすること','Integration took several months.']
    ],
    synonym: [
      ['obtain','get','得る','They obtained permission to proceed.'],
      ['distribution','spread','分布・広がり','The map shows the distribution.'],
      ['aspect','feature','側面・特徴','Focus on one aspect of the problem.'],
      ['impact','effect','影響','The change had a lasting impact.'],
      ['domain','field','分野','She works in this research domain.'],
      ['publish','release','発表する','They will publish the findings.'],
      ['denote','indicate','示す','The letter denotes a variable.'],
      ['cognitive','mental','認知・思考の','The task requires cognitive effort.'],
      ['correlation','association','相関・関連','There is a clear correlation.'],
      ['induce','cause','引き起こす','Stress may induce headaches.'],
      ['finite','limited','限りのある','Time is finite.'],
      ['stimulus','trigger','刺激・きっかけ','The sound was the stimulus.'],
      ['transformation','change','変化','The city underwent a transformation.'],
      ['equilibrium','balance','均衡','The system returned to equilibrium.'],
      ['intensity','strength','強さ','We measured the intensity.'],
      ['duration','length','継続時間','The duration was five minutes.'],
      ['optimal','best','最適な','Choose the optimal method.'],
      ['explicit','clear','明確な','The rule must be explicit.'],
      ['prediction','forecast','予測','The prediction was accurate.'],
      ['identical','same','同一の','The two samples are identical.']
    ]
  }
};
