// Each entry is one intentional match. A duplicate English word never appears in the same deck.
window.KOTOBA_WORDS = {
  translation: [
    ['bright','明るい','明るい・輝いている','The room is bright in the morning.'],
    ['journey','旅','旅行・道のり','The journey took three days.'],
    ['forest','森','森林','We walked through the forest.'],
    ['curious','好奇心の強い','知りたがる','She is curious about science.'],
    ['gentle','優しい','穏やかな','He spoke in a gentle voice.'],
    ['improve','改善する','より良くする','Practice can improve your skills.'],
    ['discover','発見する','初めて見つける','They discovered a new path.'],
    ['patient','忍耐強い','辛抱強い','Please be patient with yourself.'],
    ['ancient','古代の','とても昔の','This is an ancient city.'],
    ['brave','勇敢な','恐れずに行動する','It was brave of her to speak up.'],
    ['quiet','静かな','音が少ない','The street was quiet at night.'],
    ['simple','簡単な','複雑でない','The answer is simple.'],
    ['honest','正直な','うそをつかない','Thank you for being honest.'],
    ['rare','珍しい','めったにない','It is rare to see this bird.'],
    ['gather','集める','一か所に集める','We gather leaves in autumn.'],
    ['protect','守る','危険から守る','Trees protect the soil.'],
    ['create','作り出す','新しく作る','They create art together.'],
    ['arrive','到着する','目的地に着く','We arrive before noon.'],
    ['choose','選ぶ','複数から決める','Choose a book you like.'],
    ['support','支える','助ける・支援する','Friends support each other.'],
    ['reduce','減らす','量を小さくする','We need to reduce waste.'],
    ['explain','説明する','分かるように伝える','Can you explain the rule?'],
    ['remember','覚えている','忘れずにいる','I remember that day.'],
    ['prepare','準備する','前もって用意する','Prepare for the trip.'],
    ['promise','約束する','すると誓う','I promise to help you.'],
    ['wonder','不思議に思う','疑問を抱く','I wonder what happened.'],
    ['comfortable','快適な','心地よい','This chair is comfortable.'],
    ['valuable','価値のある','大切で役立つ','Your advice is valuable.']
  ],
  synonym: [
    ['happy','glad','うれしい','She was happy to see her friend.'],
    ['begin','start','始める','Let us begin the lesson.'],
    ['large','big','大きい','They live in a large house.'],
    ['quick','fast','速い','He gave a quick reply.'],
    ['clever','smart','賢い','That was a clever idea.'],
    ['silent','quiet','静かな','The room was silent.'],
    ['angry','mad','怒っている','She was angry about the mistake.'],
    ['tiny','small','とても小さい','A tiny bird sat on the branch.'],
    ['difficult','hard','難しい','This question is difficult.'],
    ['beautiful','pretty','美しい','The garden is beautiful.'],
    ['ill','sick','病気の','He felt ill yesterday.'],
    ['finish','complete','終える','We will finish the project today.'],
    ['assist','help','助ける','Can you assist me?'],
    ['purchase','buy','買う','They plan to purchase a car.'],
    ['reply','answer','答える','Please reply to my question.'],
    ['select','choose','選ぶ','Select the correct answer.'],
    ['calm','peaceful','穏やかな','The lake was calm.'],
    ['wealthy','rich','裕福な','The wealthy family donated money.'],
    ['rapid','swift','素早い','The river has a rapid flow.'],
    ['safe','secure','安全な','Keep your passport safe.'],
    ['idea','thought','考え','That is an interesting idea.'],
    ['error','mistake','間違い','I found an error in the report.'],
    ['neat','tidy','整った','Her desk is neat.'],
    ['look','see','見る','Look at the sky.'],
    ['dull','boring','退屈な','The film was dull.'],
    ['afraid','scared','怖がっている','The child was afraid of the storm.'],
    ['gift','present','贈り物','She gave him a gift.'],
    ['kind','friendly','親切な','Our neighbor is kind.']
  ]
};
